Olog/phoebus-olog

.gitignore
src/main/java/gov/bnl/olog/security/SessionFilter.java
src/test/java/gov/bnl/olog/security/SessionFilterTest.java
src/test/java/gov/bnl/olog/security/SessionFilterTestConfig.java
src/test/resources/session_test.properties

Fix for CI build errors due to mistake in .gitignore.

Issue_6 update to .gitignore as it excluded required files

---

pom.xml
src/main/java/gov/bnl/olog/ContentTypeResolver.java
src/main/java/gov/bnl/olog/LogRepository.java
src/main/java/gov/bnl/olog/LogResource.java
src/test/java/gov/bnl/olog/ContentTypeResolvertest.java
src/test/java/gov/bnl/olog/LogResourceIT.java

Added dependency to Apache Tika, which provides functionality to detect content types.

Issue_17 Add content type header for attachment download

---

src/main/java/gov/bnl/olog/LogSearchUtil.java
src/main/java/gov/bnl/olog/entity/Log.java
src/test/java/gov/bnl/olog/LogRepositorySearchIT.java

Also fixed equals method on Log as level field is not enum anymore.

Issue_32 Add support for search on level

---

src/main/java/gov/bnl/olog/LogRepository.java
src/main/java/gov/bnl/olog/LogbookRepository.java
src/main/java/gov/bnl/olog/LogbooksResource.java
src/main/java/gov/bnl/olog/PropertiesResource.java
src/main/java/gov/bnl/olog/PropertyRepository.java
src/main/java/gov/bnl/olog/TagRepository.java
src/main/java/gov/bnl/olog/TagsResource.java

Spotted by deployment team: logger entry pointed to wrong class due to reuse of statically created logger objects.

Adding separate logger to replace static ones

---

src/main/java/gov/bnl/olog/WebSecurityConfig.java
src/main/resources/application.properties

Had to add some LDAP related parameters to make things (e.g. group search) work at ESS. Cannot verify on different LDAP/AD setup, so this should be verified prior to merge.

Issue_42 Additional LDAP config parameters

---

src/main/java/org/phoebus/olog/LogRepository.java
src/main/java/org/phoebus/olog/LogResource.java
src/main/java/org/phoebus/olog/entity/Log.java
src/test/java/org/phoebus/olog/LogResourceTest.java
src/test/java/org/phoebus/olog/LogResourceTestConfig.java

Needed in order to be able to create links/relations.

Added update log endpoint

---

.project
Dockerfile
README.md
docker-compose.yml
pom.xml
src/main/java/org/phoebus/olog/Application.java
src/site/sphinx/index.rst

Updating documentation and pom and other project files to match the new phoebus-olog

refactor for the new Phoebus Olog

---

src/main/java/org/phoebus/olog/LogSearchUtil.java
src/main/resources/application.properties

Issue_73, handle limit search parameter

---

.gitignore
docker-compose.yml
pom.xml
src/main/java/org/phoebus/olog/AttachmentResource.java
src/main/java/org/phoebus/olog/LogRepository.java
src/main/java/org/phoebus/olog/LogResource.java
src/main/java/org/phoebus/olog/LogSearchUtil.java
src/main/java/org/phoebus/olog/LogbookRepository.java
src/main/java/org/phoebus/olog/LogbooksResource.java
src/main/java/org/phoebus/olog/PropertiesResource.java
src/main/java/org/phoebus/olog/PropertyRepository.java
src/main/java/org/phoebus/olog/TagRepository.java
src/main/java/org/phoebus/olog/TagsResource.java
src/main/java/org/phoebus/olog/entity/Property.java
src/main/resources/application-docker.properties
src/test/java/org/phoebus/olog/LogbookResourceTest.java
src/test/java/org/phoebus/olog/PropertiesResourceTest.java
src/test/java/org/phoebus/olog/docker/ITTestFixture.java
src/test/java/org/phoebus/olog/docker/ITUtil.java
src/test/java/org/phoebus/olog/docker/OlogIT.java
src/test/java/org/phoebus/olog/docker/OlogLogbooksIT.java
src/test/java/org/phoebus/olog/docker/OlogLogsIT.java
src/test/java/org/phoebus/olog/docker/OlogLogsQueryIT.java
src/test/java/org/phoebus/olog/docker/OlogPropertiesIT.java
src/test/java/org/phoebus/olog/docker/OlogTagsIT.java

Handle non-existing logbooks, tags and properties #70.
Adjustments for backend with adjustments for related unit tests. Example of adjustment is to not return null for query by id if not found, instead return exception not found with status 404 Not Found.
Added dockerized integration tests (src/test/java/.../docker) that starts the application and tests REST API calls including fill of Elastic with example content and test of query by pattern for example content.

Issue 70 backend adjustments it

---

src/main/java/org/phoebus/olog/LogSearchUtil.java

Turns out usage of ``java.time.Instant`` can be a bit challenging. I've updated such that other APIs are used instead, and time zone is considered. The price to pay is loss of millisecond precision.

Fix for date/time search

---

src/site/sphinx/changelog.rst
src/site/sphinx/index.rst

@georgweiss I added the basic change log... please expand it as needed.

Adding basic changelog to the documentation

---

src/main/java/org/phoebus/olog/HelpResource.java

Will need a new release. Sorry.

Fix for help content

---

pom.xml

Ran some smoke tests, no issues detected.

Update jackson as suggested by Github bot

---

src/main/java/org/phoebus/olog/InfoResource.java
src/main/java/org/phoebus/olog/MongoConfig.java
src/main/resources/application.properties
src/test/resources/test_application.properties

Main impact of this fix is that the connection parameters must be:
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ologAttachments

Fix for MongoDB connection configuration

---

src/main/java/org/phoebus/olog/LogSearchUtil.java
src/main/resources/static/SearchHelp_en.html

Trigger phrase query in quoted desc values, multiple values and:ed

---

src/main/java/org/phoebus/olog/LogRepository.java
src/main/java/org/phoebus/olog/LogSearchUtil.java
src/main/resources/static/SearchHelp_en.html
src/test/java/org/phoebus/olog/LogSearchUtilTest.java

Will merge as this is pretty urgent

Fix parsing of desc search terms

---

.github/workflows/docker-publish-image.yml

See output of latest trigger: https://github.com/Olog/phoebus-olog/actions/runs/4315261132/jobs/7529388499

Enable docker image push

---

.github/workflows/docker-publish-image.yml

Run failed due to not being authenticated to Github Container Registry

cicd: fix: not authenticated to ghcr.io

---

.github/workflows/java-build-and-test.yml

cicd: upgrade setup-java GH action to v3, specify distribution

CSSTUDIO-1844: Upgrade setup-java GH action

---

src/main/java/org/phoebus/olog/Application.java
src/main/java/org/phoebus/olog/FileUploadSizeExceededHandler.java
src/main/java/org/phoebus/olog/HttpConnectorConfig.java
src/main/java/org/phoebus/olog/InfoResource.java
src/main/java/org/phoebus/olog/LogResource.java
src/main/java/org/phoebus/olog/entity/Attachment.java
src/main/resources/application.properties
src/site/sphinx/index.rst
src/test/java/org/phoebus/olog/LogResourceTest.java

Try to merge in order to sync up with the changes to support editing.

Csstudio 1818

---

src/main/java/org/phoebus/olog/ElasticConfig.java

Adds configuration for the keep-alive timeout for the underlying http client used for elastic
```elasticsearch.http.keep_alive_timeout_ms```
Default is 30000ms (30 seconds)

add configuration for http client keepalive timeout elastic

---

src/site/sphinx/index.rst

Fix the example json for multiple part example describing log entries with attachments

Fix the  example for attachment

---

pom.xml

https://github.com/ControlSystemStudio/phoebus/pull/3153

reproducible builds, include git commit info and git commit time
