Olog/phoebus-olog

.gitignore, pom.xml, src/main/java/gov/bnl/olog/LogResource.java, src/main/java/gov/bnl/olog/LogbooksResource.java, src/main/java/gov/bnl/olog/MongoConfig.java, src/main/java/gov/bnl/olog/PropertiesResource.java, src/test/java/gov/bnl/olog/LogResourceTest.java, src/test/java/gov/bnl/olog/LogbookResourceTest.java, src/test/java/gov/bnl/olog/PropertiesResourceTest.java, src/test/java/gov/bnl/olog/ResourcesTestBase.java, src/test/java/gov/bnl/olog/ResourcesTestConfig.java, src/test/resources/no_ldap_test_application.properties
Using Spring's ability to inject the Principal for each controller method, added this to create methods to set the owner field as defined by the logged in user's credentials.
Decided to not update owner field for update methods, but maybe we should...?
Also added unit tests.
=> Issue_7 Use principal's id to set the owner field. Also added unit tests

.gitignore, pom.xml, src/main/java/gov/bnl/olog/Application.java, src/main/java/gov/bnl/olog/AuthenticationResource.java, src/main/java/gov/bnl/olog/ElasticConfig.java, src/main/java/gov/bnl/olog/LogbooksResource.java, src/main/java/gov/bnl/olog/WebSecurityConfig.java, src/main/java/gov/bnl/olog/entity/UserData.java, src/main/resources/application.properties, src/test/java/gov/bnl/olog/AuthenticationResourceTest.java, src/test/java/gov/bnl/olog/AuthenticationResourceTestConfig.java, src/test/java/gov/bnl/olog/LogResourceTest.java, src/test/java/gov/bnl/olog/LogbookResourceTest.java, src/test/java/gov/bnl/olog/PropertiesResourceTest.java, src/test/java/gov/bnl/olog/ResourcesTestConfig.java
The solution is based on a servlet filter that will look for a session cookie or basic authentication header  in order to establish whether the request is allowed or not. Using a session cookie will be more efficient as a remote authentication service need not be called.
Also added a controller providing a login endpoint. Successful login will create a session and return a cookie to the client, which should use it in subsequent requests. A logout endpoint can be called to delete the session.
Sessions are managed in a H2 in-memory database. In this first version of the session management this in-memory solution means that a service restart will wipe all sessions. Extending to a file-based H2 database should be straight forward. 
In order to use the Spring JdbcIndexedSessionRepository an …
=> Issue_6 adding security logic to support session based authentication

src/main/java/gov/bnl/olog/ElasticConfig.java, src/main/java/gov/bnl/olog/LogSearchUtil.java, src/main/java/gov/bnl/olog/entity/Log.java, src/main/resources/log_template_mapping_with_title.json, src/test/java/gov/bnl/olog/LogRepositorySearchIT.java
Addition of title is done as a second step in ElasticConfig, which also adds a version number to the template. Verified on existing template as well as on new template (create = true). The two step procedure mimics FlyWay in a sense.
Integration tests seem to run, including search on title.
=> Issue_15 Add title to the olog template

src/main/java/gov/bnl/olog/LogResource.java, src/main/resources/application.properties
Also added application properties to override default file upload and request size as these limit the upload size to 1MB per file.
=> Issue_19 Synchronized attachement upload end point

src/main/java/gov/bnl/olog/AttachmentRepository.java, src/main/java/gov/bnl/olog/AttachmentResource.java, src/main/java/gov/bnl/olog/InfoResource.java, src/main/java/gov/bnl/olog/LogResource.java, src/main/java/gov/bnl/olog/MongoConfig.java, src/main/java/gov/bnl/olog/OlogResourceDescriptors.java, src/main/resources/static/CommonmarkCheatsheet.html, src/test/java/gov/bnl/olog/AttachmentResourceTest.java, src/test/java/gov/bnl/olog/ResourcesTestConfig.java
The cheatsheet is served on `http(s)://<host>/CommonmarkCheatsheet.html`.
There are no dependencies in the html to external resources, so off-line clients should be able to render it correctly.
=> Adding Commonmark cheatsheet + user defined ids

pom.xml, src/main/java/gov/bnl/olog/LogResource.java, src/main/java/gov/bnl/olog/PreProcessorConfig.java, src/main/java/gov/bnl/olog/entity/Log.java, src/main/java/gov/bnl/olog/entity/preprocess/CommonmarkPreprocessor.java, src/main/java/gov/bnl/olog/entity/preprocess/DefaultPreprocessor.java, src/main/java/gov/bnl/olog/entity/preprocess/LogPreprocessor.java, src/test/java/gov/bnl/olog/entity/preprocess/CommonmarkPreprocessorTest.java, src/test/java/gov/bnl/olog/entity/preprocess/DefaultPreprocessorTest.java
In order to ensure that both description and source fields are set correctly, I've added "pre-processors". One is used for clients that do not use markup, the other is for Commonmark. To make this work as intended for the Commonmark case, client will need to send request parameter `markup=commonmark`. 
The implementation relies on the fact that clients currently do not set the source field, i.e. any text - whether using markup or not - is provided in the description field of the Log class.
The web client is updated to use the proper request parameter value, the Phoebus client is pending a PR.
=> Add pre-processors to convert markup to plain text

src/main/java/gov/bnl/olog/LogResource.java, src/main/java/org/phoebus/util/time/TimeInterval.java, src/main/java/org/phoebus/util/time/TimeParser.java, src/main/java/org/phoebus/util/time/TimeRelativeInterval.java, src/main/java/org/phoebus/util/time/TimestampFormats.java, src/test/java/org/phoebus/util/time/TimeIntervalTest.java, src/test/java/org/phoebus/util/time/TimeParserTest.java, src/test/java/org/phoebus/util/time/TimeRelativeIntervalTest.java
In order to support date/time expressions like "12 hours" or "2 days" across all clients, I've added parsing code copied from the Phoebus project. Of course a maven dependency would be preferable...
The change is backwards compatible, i.e. client may choose to perform the same parsing of such expressions, but server will call the parsing code anyway.
=> Adding parsing of date/time expressions

src/main/java/org/phoebus/olog/LogRepository.java, src/main/java/org/phoebus/olog/LogResource.java, src/main/java/org/phoebus/olog/entity/SearchResult.java, src/test/java/org/phoebus/olog/LogRepositorySearchIT.java, src/test/java/org/phoebus/olog/LogResourceTest.java
So I added end point ``Olog/logs/search`` to separate it from current end point ``Olog/logs`` used for search. Response is a new simple wrapper class ``SearchResult``.
=> Issue_100: inlcude hit count in search response

src/main/resources/application.properties
Not sure why this has not yet been reported by users, but the CommonmarkCheatsheet.html resource will not be available if a the Olog web front-end is deployed in a particular manner.
This PR should make the static resource handling more robust. 
Phoebus Olog client change is needed and will be pushed.
=> Fix for static resources handling

src/main/java/org/phoebus/olog/LogSearchUtil.java, src/main/resources/static/SearchHelp_en.html, src/site/sphinx/index.rst
To make client implementations simpler, attachments=all is supported to handle search for log entries with attachments of any type.
Also minor documentation addition.
=> Bug fix and minor change in attachment search

src/main/java/org/phoebus/olog/LogResource.java, src/main/java/org/phoebus/olog/entity/preprocess/impl/CommonmarkCleaner.java, src/test/java/org/phoebus/olog/LogResourceTest.java, src/test/java/org/phoebus/olog/entity/preprocess/CommonmarkPreprocessorTest.java
As discussed over email:
The update operation should do the same thing as when creating a log entry, i.e. client should send only source, server should process source to populate description
Based on this I made the following changes:
In POST mapping for log entry, applied cleanMarkup to log as is done in PUT mapping.
In CommonmarkCleaner, processed the source field to clean the markup tags and wrote it to description field.
Updated unit tests to match the above changes.
Made sure the server supports the current UI client(web), which sends log entry's source in description field in PUT API.
=> POST API support

docker-compose.yml, src/main/java/org/phoebus/olog/ElasticConfig.java, src/main/resources/application-docker.properties
When starting the docker-compose stack, the services will all appear to have started; however creation of indexes, loading of development data, etc. will all have failed. So, when running the docker integration tests or just trying to GET tags etc via Postman the Java service will respond with HTTP 500 due to the connection being either refused or with a 404 due to search failing to find the expected results.
This is due to (1) starting the olog service before the cluster was fully ready, and (2) security/ssl not correctly disabled for local development. 
NOTE: 
While setting the xpack.security variables in the docker compose environment is sufficient to startup the local cluster with security disabled in development, it is also necessary to specify the protocol as http in the …
=> Fix: HTTP 500 Connection Refused when using Docker Compose development environment

src/main/java/org/phoebus/olog/LogSearchUtil.java, src/main/resources/static/SearchHelp_en.html
It makes sense to support case insensitive search on certain fields:
- owner/user
- tag name
- property name
- property attribute name
- property attribute value
This PR implements this. Documentation updated accordingly.
=> Case insensitive search

src/main/java/org/phoebus/olog/LogRepository.java, src/main/java/org/phoebus/olog/entity/Log.java
@shroffk, need to flush immediately when updating log entry. Otherwise a search triggered by client when update call returns may return a stale entry.
Also some changes to get rid of lint warnings in ```Log``` class.
=> Flush immediately on log entry update

src/main/java/org/phoebus/olog/ElasticConfig.java
Adds configuration for timeout and master_timeout for the create index operation, needed in slow envs such as CI/CD on GitHub where index creation can take a while but fails due to the default timeout (30s).
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html
> master_timeout
> (Optional, [time units](https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conventions.html#time-units)) Period to wait for a connection to the master node. If no response is received before the timeout expires, the request fails and returns an error. Defaults to 30s.
> timeout
> (Optional, [time units](https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conventions.html#time-units)) Period to wait for a response. If no response is received …
=> add configurability for index creation timeouts

src/main/java/org/phoebus/olog/ElasticConfig.java
Adds socket and connect timeout configuration, see https://github.com/elastic/elasticsearch/issues/65213
(sorry about the number of PRs for this -- it's difficult to test/force a timeout locally, so it has been a bit of stabbing in the dark)
```
elasticsearch.http.connect_timeout_ms
elasticsearch.http.socket_timeout_ms
```
=> add socket and connect timeout config

pom.xml, src/main/resources/application.properties
Changes:
- Adds support for openapi/swagger autogenerated API docs 
- UI available at at http://localhost:8080/api/docs 
- JSON available at http://localhost:8080/api/spec
- Uses the autogenerated docs as-is; does not currently add additional annotations to the swagger docs to e.g. name resources, use tags, etc
- Shows operation ids (generated from controller method names, or disambiguated if there are duplicates)
Fixes:
- upgrades maven-javadoc-plugin to fix MJAVADOC-650 for Java 9+
=> CSSTUDIO-2026: add openapi/swagger + javadoc fix.

.readthedocs.yaml, src/site/sphinx/conf.py, src/site/sphinx/requirements.txt
This is the same as the PR to channel finder - https://github.com/ChannelFinder/ChannelFinderService/pull/126
RTD now requires a configure file for the builds to work - https://readthedocs.org/projects/olog/builds/
Removed recommonmark from conf.py since it is deprecated and there are no .md files in src/site/sphinx anyways
=> add readthedocs config file

src/main/java/org/phoebus/olog/LogResource.java, src/test/java/org/phoebus/olog/docker/ITUtilLogs.java, src/test/java/org/phoebus/olog/docker/OlogLogsIT.java, src/test/resources/INTEGRATIONTEST_DOCKER_RUN.md
Log entry group property should not be editable but remain if it exists.
Integration test made available
- src/test/java/org/phoebus/olog/docker/OlogLogsIT.java
- @Test void handleLogGroup() {
- see src/test/resources/INTEGRATIONTEST_DOCKER_RUN.md for instructions on how to compile and run integration test
=> Log entry group property not editable

docker-compose-integrationtest.yml, docker-compose.yml
When starting the ecosystem / services with docker compose, the backend fails to communicate with elastic and mongo db.
This is because in the compose networking environment the service hosts are the names of the services (elastic, mongo, etc) rather than localhost. 
This fixes that configuration issue for local development, and also adds localhost:3000 as an allowed cors origin so that local frontend development can speak to the server as well.
=> fix: set host vars in docker compose

src/test/java/org/phoebus/olog/docker/ITUtil.java, src/test/java/org/phoebus/olog/docker/ITUtilLogbooks.java, src/test/java/org/phoebus/olog/docker/ITUtilLogs.java, src/test/java/org/phoebus/olog/docker/ITUtilProperties.java, src/test/java/org/phoebus/olog/docker/ITUtilTags.java, src/test/java/org/phoebus/olog/docker/OlogIT.java, src/test/java/org/phoebus/olog/docker/OlogLogbooksIT.java, src/test/java/org/phoebus/olog/docker/OlogLogsIT.java, src/test/java/org/phoebus/olog/docker/OlogLogsQueryIT.java, src/test/java/org/phoebus/olog/docker/OlogPropertiesIT.java, src/test/java/org/phoebus/olog/docker/OlogTagsIT.java, src/test/resources/INTEGRATIONTEST_DOCKER_RUN.md, src/test/resources/INTEGRATIONTEST_DOCKER_TUTORIAL.md
Use Java HttpClient instead of curl and HttpURLConnection for integration test.
=> Integration test http client

pom.xml
This Pull Request fixes `spring-boot-maven-plugin` to a specific version. Else, maven will always pick the latest version of the plugin, which makes the project dependencies not reproducible.
This can be problematic, because when building older versions of phoebus-olog, maven will use a different version of `spring-boot-maven-plugin` than the one that was available when the version was released.
I've chosen the latest version, because that's the one that is currently in use, but since it seems like a beta release, it might make sense to choose a different one.
=> fix version of spring-boot-maven-plugin in pom.xml

pom.xml, src/main/java/org/phoebus/olog/InfoResource.java, src/main/java/org/phoebus/olog/LogResource.java, src/main/java/org/phoebus/olog/OlogResourceDescriptors.java, src/main/java/org/phoebus/olog/entity/websocket/MessageType.java, src/main/java/org/phoebus/olog/entity/websocket/WebSocketMessage.java, src/main/java/org/phoebus/olog/websocket/WebSocketConfig.java, src/main/java/org/phoebus/olog/websocket/WebSocketController.java, src/main/java/org/phoebus/olog/websocket/WebSocketService.java, src/main/resources/application.properties, src/test/java/org/phoebus/olog/LogResourceTest.java, src/test/java/org/phoebus/olog/LogResourceTestConfig.java
This adds web socket support, STOMP style. Intention is to notify clients in the following cases:
1. New log entry created -> clients will need to refresh search view
2. A log entry has been updated -> clients may wish to notify user if that log entry is "in focus"
3. Show banner: this is for future use, e.g. web client banner to show that service is being restarted, upcoming client update, upcoming maintenance work and potential disruptions etc.
The service setup is to employ a 30 s heartbeat. Clients must also connect with a non-zero heartbeat strategy.
=> Web sockets for client notifications 
